/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface XuiButton {
    'disabled': boolean;
    'ghost': boolean;
    'inverted': boolean;
    'text': string;
    'type': 'default' | 'primary' | 'danger';
  }
  interface XuiColor {
    'color': string;
    'steps': number;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLXuiButtonElement extends Components.XuiButton, HTMLStencilElement {}
  var HTMLXuiButtonElement: {
    prototype: HTMLXuiButtonElement;
    new (): HTMLXuiButtonElement;
  };

  interface HTMLXuiColorElement extends Components.XuiColor, HTMLStencilElement {}
  var HTMLXuiColorElement: {
    prototype: HTMLXuiColorElement;
    new (): HTMLXuiColorElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'xui-button': HTMLXuiButtonElement;
    'xui-color': HTMLXuiColorElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface XuiButton extends JSXBase.HTMLAttributes<HTMLXuiButtonElement> {
    'disabled'?: boolean;
    'ghost'?: boolean;
    'inverted'?: boolean;
    'text'?: string;
    'type'?: 'default' | 'primary' | 'danger';
  }
  interface XuiColor extends JSXBase.HTMLAttributes<HTMLXuiColorElement> {
    'color'?: string;
    'steps'?: number;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'xui-button': XuiButton;
    'xui-color': XuiColor;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


